from dash_bootstrap_components import (
    Offcanvas,
    Row,
    Col,
    Card,
    CardBody,
)
from dash.html import Br, Hr, Span
from dash_mantine_components import (
    Button,
    CheckboxGroup,
    Checkbox,
    RangeSlider,
    TextInput,
    RadioGroup,
    Radio,
)

from utils.controls import create_multiselect


def create_filter_canvas(
    sort_control,
    liquor_control,
    syrups_control,
    garnish_control,
    other_control,
    bitters_control,
    recipe_count,
) -> Offcanvas:
    return (
        Offcanvas(
            [
                Row(
                    Col(
                        Card(
                            CardBody(
                                [
                                    Row(
                                        [
                                            Col(
                                                [
                                                    Button(
                                                        "Apply Filters",
                                                        id="apply-filters-button",
                                                        n_clicks=0,
                                                        color="orange",
                                                    )
                                                ],
                                            ),
                                            Col(
                                                [
                                                    Button(
                                                        "Reset All Filters",
                                                        id="reset-filters-button",
                                                        n_clicks=0,
                                                        color="orange",
                                                    )
                                                ]
                                            ),
                                        ],
                                    ),
                                ]
                            )
                        )
                    )
                ),
                Row(
                    Col(
                        Card(
                            CardBody(
                                [
                                    create_multiselect(
                                        id="sort-by-dropdown",
                                        label="Sort By...",
                                        data=sort_control,
                                    )[0],
                                    RadioGroup(
                                        id="sort-by-radio",
                                        children=[
                                            Radio(
                                                label="Ascending",
                                                value=True,
                                                color="orange",
                                            ),
                                            Radio(
                                                label="Descending",
                                                value=False,
                                                color="orange",
                                            ),
                                        ],
                                        value=True,
                                        size="md",
                                        persistence=True,
                                        persistence_type="session",
                                    ),
                                ]
                            )
                        )
                    )
                ),
                Row(
                    [
                        Col(
                            [
                                Card(
                                    CardBody(
                                        [
                                            Row(
                                                Col(
                                                    [
                                                        CheckboxGroup(
                                                            id="ingredients-checklist",
                                                            orientation="horizontal",
                                                            label="Show Cocktails Where I...",
                                                            offset="md",
                                                            size="md",
                                                            pb=15,
                                                            children=[
                                                                Checkbox(
                                                                    label="Have All Ingredients",
                                                                    value="have_all",
                                                                    color="orange",
                                                                ),
                                                                Checkbox(
                                                                    label="Have Some Ingredients",
                                                                    value="have_some",
                                                                    color="orange",
                                                                ),
                                                                Checkbox(
                                                                    label="Have No Ingredients",
                                                                    value="have_none",
                                                                    color="orange",
                                                                ),
                                                            ],
                                                            value=[
                                                                "have_all",
                                                                "have_some",
                                                                "have_none",
                                                            ],
                                                            persistence=True,
                                                            persistence_type="session",
                                                        ),
                                                        Br(),
                                                        Hr(),
                                                        CheckboxGroup(
                                                            id="include-garnish-checkbox",
                                                            orientation="horizontal",
                                                            offset="md",
                                                            size="md",
                                                            pb=15,
                                                            children=Checkbox(
                                                                label="Include Garnishes?",
                                                                value="include_garnishes",
                                                                color="orange",
                                                            ),
                                                            value=["include_garnishes"],
                                                            persistence=True,
                                                            persistence_type="session",
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    )
                                )
                            ]
                        )
                    ]
                ),
                Row(
                    [
                        Col(
                            [
                                Card(
                                    CardBody(
                                        [
                                            Row(
                                                Col(
                                                    [
                                                        CheckboxGroup(
                                                            id="favorites-bookmarks-unrated-checklist",
                                                            orientation="horizontal",
                                                            offset="md",
                                                            size="md",
                                                            pb=15,
                                                            children=[
                                                                Checkbox(
                                                                    label="Show Favorites Only",
                                                                    value="favorites_only",
                                                                    color="orange",
                                                                ),
                                                                Checkbox(
                                                                    label="Show Bookmarks Only",
                                                                    value="bookmarks_only",
                                                                    color="orange",
                                                                ),
                                                                Checkbox(
                                                                    label="Include Unrated Cocktails",
                                                                    value="include_unrated",
                                                                    color="orange",
                                                                ),
                                                            ],
                                                            value=[
                                                                None,
                                                                None,
                                                                "include_unrated",
                                                            ],
                                                            persistence=True,
                                                            persistence_type="session",
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    )
                                )
                            ]
                        )
                    ]
                ),
                Row(
                    [
                        Col(
                            [
                                Card(
                                    CardBody(
                                        [
                                            Span(
                                                "Cocktail NPS Range",
                                                className="dmc-range-slider",
                                            ),
                                            RangeSlider(
                                                id="cocktail-nps-range-slider",
                                                min=-100,
                                                max=100,
                                                step=10,
                                                value=[-100, 100],
                                                marks=[
                                                    {
                                                        "value": i,
                                                        "label": "{}".format(
                                                            i if i % 20 == 0 else ""
                                                        ),
                                                    }
                                                    for i in range(
                                                        -100,
                                                        101,
                                                        10,
                                                    )
                                                ],
                                                minRange=9,
                                                color="orange",
                                                pb=25,
                                                showLabelOnHover=False,
                                                persistence=True,
                                                persistence_type="session",
                                            ),
                                        ]
                                    )
                                )
                            ],
                        )
                    ]
                ),
                Row(
                    [
                        Col(
                            [
                                Card(
                                    CardBody(
                                        create_multiselect(
                                            id="liquor-dropdown",
                                            label="Liquor",
                                            data=liquor_control,
                                        ),
                                    )
                                )
                            ],
                        )
                    ]
                ),
                Row(
                    [
                        Col(
                            [
                                Card(
                                    CardBody(
                                        create_multiselect(
                                            id="syrup-dropdown",
                                            label="Syrup",
                                            data=syrups_control,
                                        ),
                                    )
                                )
                            ],
                        ),
                    ]
                ),
                Row(
                    [
                        Col(
                            [
                                Card(
                                    CardBody(
                                        create_multiselect(
                                            id="bitter-dropdown",
                                            label="Bitters",
                                            data=bitters_control,
                                        ),
                                    )
                                )
                            ],
                        ),
                    ]
                ),
                Row(
                    [
                        Col(
                            [
                                Card(
                                    CardBody(
                                        create_multiselect(
                                            id="garnish-dropdown",
                                            label="Garnish",
                                            data=garnish_control,
                                        ),
                                    )
                                )
                            ],
                        )
                    ]
                ),
                Row(
                    [
                        Col(
                            [
                                Card(
                                    CardBody(
                                        create_multiselect(
                                            id="other-dropdown",
                                            data=other_control,
                                            label="Other Ingredients",
                                        ),
                                    )
                                )
                            ],
                        )
                    ]
                ),
                Row(
                    [
                        Col(
                            [
                                Card(
                                    CardBody(
                                        [
                                            TextInput(
                                                id="free-text-search",
                                                type="text",
                                                label="Free Text Search",
                                                placeholder="RegEx search here...",
                                                debounce=True,
                                                persistence=True,
                                                persistence_type="session",
                                            )
                                        ]
                                    )
                                )
                            ],
                        ),
                    ]
                ),
                Row(
                    [
                        Col(
                            [
                                Card(
                                    CardBody(
                                        [
                                            Row(
                                                [
                                                    Col(
                                                        [
                                                            RadioGroup(
                                                                id="filter-type",
                                                                children=[
                                                                    Radio(
                                                                        "AND",
                                                                        value="and",
                                                                        color="orange",
                                                                    ),
                                                                    Radio(
                                                                        "OR",
                                                                        value="or",
                                                                        color="orange",
                                                                    ),
                                                                ],
                                                                value="and",
                                                                label="Filter Type",
                                                                size="md",
                                                                persistence=True,
                                                                persistence_type="session",
                                                            ),
                                                        ],
                                                    ),
                                                ],
                                            ),
                                        ]
                                    )
                                )
                            ],
                        ),
                    ]
                ),
            ],
            id="offcanvas-scrollable",
            scrollable=True,
            title=f"Filters (Showing {recipe_count} Recipes)",
            is_open=False,
        ),
    )
